In [43]:
import pydicom
import cv2
import numpy as np

# Đường dẫn đến file DICOM
dicom_path = r"C:\Users\ASUS TUF\Documents\Kidney Stone Dataset\manifest-1592488683281\C4KC-KiTS\KiTS-00036\07-23-2004-NA-twophaseabdomenpelvis-41151\2.000000-arterial-16785\1-047.dcm"

# Đọc file DICOM
dicom_data = pydicom.dcmread(dicom_path)

In [51]:
# Kiểm tra và lấy thông tin Pixel Spacing
if 'PixelSpacing' in dicom_data:
    pixel_spacing = dicom_data.PixelSpacing
    print(f"Pixel Spacing: {pixel_spacing}")
    print(f"Pixel Spacing type: {type(pixel_spacing)}")
    print(f"Khoảng cách pixel theo chiều ngang (mm): {pixel_spacing[0]}")
    print(f"Khoảng cách pixel theo chiều ngang (mm): {type(pixel_spacing[0])}")
    dX = float(pixel_spacing[0])
    print(dX, type(dX))
    print(f"Khoảng cách pixel theo chiều dọc (mm): {pixel_spacing[1]}")
else:
    print("File DICOM này không chứa thông tin Pixel Spacing.")

Pixel Spacing: [0.798828125, 0.798828125]
Pixel Spacing type: <class 'pydicom.multival.MultiValue'>
Khoảng cách pixel theo chiều ngang (mm): 0.798828125
Khoảng cách pixel theo chiều ngang (mm): <class 'pydicom.valuerep.DSfloat'>
0.798828125 <class 'float'>
Khoảng cách pixel theo chiều dọc (mm): 0.798828125


In [29]:
# Trích xuất dữ liệu hình ảnh từ file DICOM
image = dicom_data.pixel_array

# Chuẩn hóa dữ liệu ảnh để hiển thị với OpenCV (chuyển giá trị pixel về 0-255)
image_normalized = cv2.normalize(image, None, 0, 255, cv2.NORM_MINMAX)
image_uint8 = image_normalized.astype(np.uint8)

print(type(image_uint8))
print(image_uint8.shape)

# Hiển thị ảnh bằng OpenCV
cv2.imshow("DICOM Image", image_uint8)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
(512, 512)


In [5]:
print(dicom_data)

Dataset.file_meta -------------------------------
(0002,0000) File Meta Information Group Length  UL: 206
(0002,0001) File Meta Information Version       OB: b'\x00\x01'
(0002,0002) Media Storage SOP Class UID         UI: CT Image Storage
(0002,0003) Media Storage SOP Instance UID      UI: 1.3.6.1.4.1.14519.5.2.1.6919.4624.302693755253199226108824913410
(0002,0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002,0012) Implementation Class UID            UI: 1.3.6.1.4.1.22213.1.143
(0002,0013) Implementation Version Name         SH: '0.5'
(0002,0016) Source Application Entity Title     AE: 'POSDA'
-------------------------------------------------
(0008,0005) Specific Character Set              CS: 'ISO_IR 100'
(0008,0008) Image Type                          CS: ['ORIGINAL', 'PRIMARY', 'AXIAL', 'CT_SOM5 SPI']
(0008,0016) SOP Class UID                       UI: CT Image Storage
(0008,0018) SOP Instance UID                    UI: 1.3.6.1.4.1.14519.5.2.1.6919.4624.30

In [ ]:
from aspose.imaging import Image
from aspose.imaging.imageoptions import JpegOptions

INPUT = r"C:\Users\ASUS TUF\Documents\Kidney Stone Dataset\manifest-1592488683281\C4KC-KiTS\KiTS-00036\07-23-2004-NA-twophaseabdomenpelvis-41151\2.000000-arterial-16785\1-047.dcm"

jpeg_options = JpegOptions()

image = Image.load(INPUT)
print(type(image))
print(image)

<class 'aspose.imaging.Image'>


In [42]:
import cv2

img = cv2.imread(r'C:\Users\ASUS TUF\Downloads\stoneInKidney_images\72_61.7089398048_1-05452817925086100001.5331535853741248033_kidney1_stone1.png')

print(img.shape)
# print(img)

# Define the range for near white pixels
lower_bound = np.array([150, 150, 150])  # Lower bound for near white
upper_bound = np.array([255, 255, 255])  # Upper bound for white
                                
# Create a mask for near white pixels
mask = cv2.inRange(img, lower_bound, upper_bound)
print(mask)

# Define the range for near white pixels
lower_bound = np.array([200, 200, 200])  # Lower bound for near white
upper_bound = np.array([255, 255, 255])  # Upper bound for white
                                
# Create a mask for near white pixels
mask = cv2.inRange(img, lower_bound, upper_bound)
print(mask)

(11, 12, 3)
[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255 255 255 255   0   0   0   0]
 [  0   0 255 255 255 255 255 255 255 255   0   0]
 [  0 255 255 255 255 255 255 255 255 255   0   0]
 [  0 255 255 255 255 255 255 255 255 255 255   0]
 [  0 255 255 255 255 255 255 255 255 255 255 255]
 [  0 255 255 255 255 255 255 255 255 255 255 255]
 [  0   0 255 255 255 255 255 255 255 255 255 255]
 [  0   0 255 255 255 255 255 255 255 255 255 255]
 [  0   0   0 255 255 255 255 255 255 255 255 255]
 [  0   0   0   0   0 255 255 255 255 255 255   0]]
[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 255 255   0   0   0   0   0]
 [  0   0   0 255 255 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255 255 255 255   0   0]
 [  0   0 255 255 255 255 255 255 255 255 255   0]
 [  0   0 255 255 255 255 255 255 255 255 255   0]
 [  0   0 255 255 255 255 255 255 255 255 255 255]
 [  0   0 255 255 255 255 255 255 255 255 255 255]
 [  0   0   0 255 